// client/components/Footer.vue
<template>
  <div class="footer">
    <ElFooter>
      <ElTabs :model-value="active" tab-position='bottom' @tab-click="handleClick">
        <ElTabPane v-for='tab of links' :key='tab.to' :name='tab.to'>
          <template #label>
            <span class="custom-tabs-label">
              <el-icon class="mr-2 mt-1">
                <component :is="tab.icon"/>
              </el-icon>
              <span>{{ tab.name }}</span>
            </span>
          </template>
        </ElTabPane>
      </ElTabs>
    </ElFooter>
  </div>
</template>

<script setup lang="ts">
import { ElTabs, ElTabPane, ElFooter, ElIcon, TabsPaneContext } from 'element-plus'
import { Calendar, Money, Guide, Coin } from '@element-plus/icons-vue'

const route = useRoute()
const router = useRouter()

const links = [
  { name: 'Cost', icon: Money, to: '/' },
  { name: 'Dist', icon: Guide, to: '/dist' },
  { name: 'DB', icon: Coin, to: '/db' },
  { name: 'Stat', icon: Calendar, to: '/stat' },
]

const active = computed(() => links.find(({ to }) => route.path.includes(to))?.to)

const handleClick = (tab: TabsPaneContext) => router.push(tab.props.name)
</script>

<style scoped lang="scss">
.footer {
  position: fixed;
  bottom: 0;
  right: 0;
  left: 0;
  height: 50px;
  display: flex;
  justify-content: center;
}
</style>

// client/components/Footer.tsx
import { For } from "solid-js";
import React from 'react'
import BottomNavigation from '@mui/material/BottomNavigation'
import BottomNavigationAction from '@mui/material/BottomNavigationAction'
import MonetizationOnIcon from '@mui/icons-material/MonetizationOn'
import DataArrayIcon from '@mui/icons-material/DataArray'
import QueryStatsIcon from '@mui/icons-material/QueryStats'
import AddBoxIcon from '@mui/icons-material/AddBox'
import { useRouter } from 'next/router'

const links = [
  { label: 'Cost', value: 'cost', icon: MonetizationOnIcon },
  { label: 'Dist', value: 'dist', icon: AddBoxIcon },
  { label: 'DB', value: 'db', icon: DataArrayIcon },
  { label: 'Stat', value: 'stat', icon: QueryStatsIcon },
]

export const Footer = () => {
  const router = useRouter()
  const [value, setValue] = React.useState('recents')

  const handleChange = async (event: React.SyntheticEvent, newValue: string) => {
    setValue(newValue)
    await router.push(`/${newValue}`)
  }

  return (
    <footer style={{ position: 'fixed', bottom: 0, right: 0, left: 0, display: 'flex', "justify-content": 'center' } }>
      <BottomNavigation sx={{ width: 500 }} value={value} onChange={handleChange}>
        <For each={links}>{link => <BottomNavigationAction key={link.value} value={link.value} label={link.label} icon={<link.icon/>} />}</For>
      </BottomNavigation >
    </footer>

  )
}
